name: Build and Test

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
# Uncomment to check formatting:
#    - name: Check Formatting
#      uses: actions-rs/cargo@v1
#      with:
#        command: fmt
#        args: -- --check
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all --all-features --exclude symphonia-play
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all --all-features --exclude symphonia-play
