name: CI

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  check:
    name: Check ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, "windows-latest"]
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Check default features
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --all
        
    - name: Check all features
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --all --all-features --exclude symphonia-play

  test:
    name: Test ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, "windows-latest"]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Setup Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Test default features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --exclude symphonia-play

      - name: Test all features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --all-features --exclude symphonia-play

      - name: Test documentation
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --all-features --doc --exclude symphonia-play


# Uncomment to check formatting
  # fmt:
  #   name: Rustfmt 

  #   runs-on: ubuntu-latest
  
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1

  #     - name: Setup Toolchain
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #         override: true

  #     - name: Check formatting
  #       uses: actions-rs/cargo@v1
  #       with:
  #         command: fmt
  #         args: --all -- --check
